Configuration:
    katcp_port: 7147
    #boffile: amisa_manual_bof_150115.bof
    #boffile: ami_fx_nofs_cf7d_2015_Jan_15_1836.bof
    #boffile: ami_fx_nofs_cf7d_2015_Jan_20_1828.bof
    #boffile: ami_fx_nofs_cf7e_2015_Jan_25_1417.bof
    #boffile: ami_fx_nofs_cf7e_2015_Jan_27_0028.bof
    #boffile: ami_fx_nofs_cf7e_2015_Jan_28_1741.bof
    #boffile: ami_fx_nofs_cf7e_2015_Feb_04_1137.bof
    #boffile: ami_fx_nofs_cf7e_2015_Feb_04_1857.bof
    #boffile: ami_fx_nofs_cf7f_2015_Feb_24_1041.bof
    #boffile: ami_fx_nofs_cf7g_2015_Feb_25_1755.bof #bad adc1 spi interface
    #boffile: ami_fx_nofs_cf7h_2015_Feb_26_2353.bof
    #boffile: amisa_2015_Mar_15_1605.bof
    #boffile: amisa_2015_Mar_17_1646.bof
    # changed autocorr capture
    #boffile: amisa_2015_Oct_15_1923.bof.gz
    #boffile: amisa_2015_Oct_16_1623.bof.gz 
    boffile: amisa_2015_Oct_19_1257.bof.gz
    redis_host: localhost
    redis_port: 6379
    control_interface:
        host: 10.1.0.10
        data_port: 2007
        meta_port: 2006
        n_ants: 10
        n_agcs: 40
    correlator:
        hardcoded:
            n_ants: 10
            n_bands: 2
            n_chans: 2040
            inputs_per_board: 2
            window_len: 1024
            output_format: l
            n_pols: 1
            # sync period is in FPGA clocks
            sync_period: 738197504
        runtime:
            fft_shift: 0b111011011011011
            ten_gbe:
                # multicast order.
                # 0 disables multicast
                # 1 subscribes each receiver to a single address
                # 2 subscribes each receiver to 2 addresses
                multicast_order: 2
                network: 10.1.10.100
                #port: 10000
            one_gbe:
                dest_ip: 10.1.1.1
                dest_mac: 0x90E2BA75D060
                port: 10000
            testing:
                ct_tvg: no
                qdr_tvg: no
                vacc_tvg: no
            data_path: /media/data0

XEngine:
    n_chans: 204
    bw_frac: 10
    n_ants: 10
    acc_len: 1024

    nodes:
        - host: amanda
          band: 0

        - host: beatrice
          band: 1

        - host: charlotte
          band: 2

        - host: daisy
          band: 3

        - host: elizabeth
          band: 4

        - host: felicity
          band: 5

        - host: grace
          band: 6

        - host: heidi
          band: 7

        - host: isabel
          band: 8

        - host: juliet
          band: 9

Array:
    # array location in degrees
    lat: 52.2050
    lon: 0.1190

Antennas:
    - ant: 0
      loc: [22.0076, 17.5829, 0.0106]
      index: 0
    - ant: 1
      loc: [12.0739, 7.7928, -0.0006]
      index: 1
    - ant: 2
      loc: [17.0683, 7.8579, -0.0161]
      index: 2
    - ant: 3
      loc: [7.2304, 17.6676, 0.0585]
      index: 3
    - ant: 4
      loc: [14.4561, 27.8043, 0.0688]
      index: 4
    - ant: 5
      loc: [22.0568, 11.2184, -0.0230]
      index: 5
    - ant: 6
      loc: [5.7293, 12.2961, 0.0366]
      index: 6
    - ant: 7
      loc: [19.6578, 23.3406, 0.0340]
      index: 7
    - ant: 8
      loc: [9.4959, 24.5802, 0.0623]
      index: 8
    - ant: 9
      loc: [14.1166, 15.8486, 0.0302]
      index: 9

FEngine:
    n_chans: 2048
    adc_power_acc_len: 2500000000
    #fft_power_acc_len counts in spectra. 1048537 is about 0.85s
    #(but at the moment it can only be a number <= 20 bits)
    fft_power_acc_len: 1048575
    adc_clk: 5000
    mix_freq: 8500
    eq_dec: 2
    eq_format: 'H'
    eq_bp: 6
    phase_switch: yes
    
    nodes:
        - ant: 0
          phase_walsh : 1
          band: low
          adc: 0
          host: amanda

        - ant: 0
          phase_walsh : 1
          band: high
          adc: 1
          host: amanda

        - ant: 1
          phase_walsh : 2
          band: low
          adc: 0
          host: beatrice

        - ant: 1
          phase_walsh : 2
          band: high
          adc: 1
          host: beatrice

        - ant: 2
          phase_walsh : 3
          band: low
          adc: 0
          host: charlotte

        - ant: 2
          phase_walsh : 3
          band: high
          adc: 1
          host: charlotte

        - ant: 3
          phase_walsh : 4
          band: low
          adc: 0
          host: daisy

        - ant: 3
          phase_walsh : 4
          band: high
          adc: 1
          host: daisy

        - ant: 4
          phase_walsh : 5
          band: low
          adc: 0
          host: elizabeth

        - ant: 4
          phase_walsh : 5
          band: high
          adc: 1
          host: elizabeth

        - ant: 5
          phase_walsh : 6
          band: low
          adc: 0
          host: felicity

        - ant: 5
          phase_walsh : 6
          band: high
          adc: 1
          host: felicity

        - ant: 6
          phase_walsh : 7
          band: low
          adc: 0
          host: grace

        - ant: 6
          phase_walsh : 7
          band: high
          adc: 1
          host: grace

        - ant: 7
          phase_walsh : 8
          band: low
          adc: 0
          host: heidi

        - ant: 7
          phase_walsh : 8
          band: high
          adc: 1
          host: heidi

        - ant: 8
          phase_walsh : 9
          band: low
          adc: 0
          host: isabel

        - ant: 8
          phase_walsh : 9
          band: high
          adc: 1
          host: isabel

        - ant: 9
          phase_walsh : 10
          band: low
          adc: 0
          host: juliet

        - ant: 9
          phase_walsh : 10
          band: high
          adc: 1
          host: juliet
