Configuration:
    katcp_port: 7147
    boffile: ami_fx_sbl_nofs_2014_Sep_30_1526.bof
    redis_host: localhost
    redis_port: 6379
    control_interface:
        host: 131.111.48.30
        data_port: 2007
        meta_port: 2006
        n_ants: 10
        n_agcs: 40
    correlator:
        hardcoded:
            n_ants: 2
            n_bands: 2
            n_chans: 2048
            inputs_per_board: 2
            window_len: 8
            output_format: l
            n_pols: 1
        runtime:
            fft_shift: 0b111011011011011
            ten_gbe:
                network: 10.0.0.0
                port: 10000
            one_gbe:
                network: 10.0.1.0
                port: 10000
            testing:
                ct_tvg: no
                qdr_tvg: no
                vacc_tvg: no
            acc_len: 152588
            data_path: /data

XEngine:
    n_chans: 2048
    n_ants: 2

    nodes:
        - band: low
          host: alice

        - band: high
          host: bob

Array:
    # array location in degrees
    lat: 52.2050
    lon: 0.1190

Antennas:
    - ant: 0
      loc: [22.0076, 17.5829, 0.0106]
      index: 9
    - ant: 1
      loc: [12.0739, 7.7928, -0.0006]
      index: 9
    - ant: 2
      loc: [17.0683, 7.8579, -0.0161]
      index: 9
    - ant: 3
      loc: [7.2304, 17.6676, 0.0585]
      index: 0
    - ant: 4
      loc: [14.4561, 27.8043, 0.0688]
      index: 9
    - ant: 5
      loc: [22.0568, 11.2184, -0.0230]
      index: 9
    - ant: 6
      loc: [5.7293, 12.2961, 0.0366]
      index: 9
    - ant: 7
      loc: [19.6578, 23.3406, 0.0340]
      index: 1
    - ant: 8
      loc: [9.4959, 24.5802, 0.0623]
      index: 9
    - ant: 9
      loc: [14.1166, 15.8486, 0.0302]
      index: 9

FEngine:
    n_chans: 2048
    adc_power_acc_len: 2500000000
    #fft_power_acc_len counts in spectra. 1048537 is about 0.85s
    #(but at the moment it can only be a number <= 20 bits)
    fft_power_acc_len: 1048575
    adc_clk: 5000
    mix_freq: 9000
    eq_dec: 2
    eq_format: 'H'
    eq_bp: 6
    
    nodes:
        - ant: 3
          band: low
          adc: 0
          host: alice
          phase_switch: yes

        - ant: 7
          band: low
          adc: 1
          host: alice
          phase_switch: no

        - ant: 3
          band: high
          adc: 0
          host: bob
          phase_switch: yes

        - ant: 7
          band: high
          adc: 1
          host: bob
          phase_switch: no

XEngines:
    - chans: 0, 2047
      host: alice

    - chans: 2048, 4095
      host: bob
